apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins
  volumes:
    - name: m2-volume
      persistentVolumeClaim:
        claimName: user01-jenkins-agent-m2
  containers:
    - name: jnlp
      image: image-registry.openshift-image-registry.svc:5000/app-devops/custom-jenkins-agent-maven
      args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
      volumemounts: 
        - mountPath: "/home/jenkins/.m2"
          name: pvc-8bde8168-8035-427a-8b39-a89027ec14de
      tty: false
      resources:
        requests:
          cpu: 500m
          memory: 1024Mi
        limits:
          cpu: 500m
          memory: 1024Mi
    - name: postgres
      image: image-registry.openshift-image-registry.svc:5000/openshift/postgresql:10
      tty: false
      env:
        - name: POSTGRESQL_USER
          value: "freelancer"
        - name: POSTGRESQL_PASSWORD
          value: "password"
        - name: POSTGRESQL_DATABASE
          value: "freelancerdb_test"
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 100m
          memory: 256Mi
